name: Setup Inno Setup and Build

on:
  push:
    branches:
      - main

jobs:
  install-inno:
    runs-on: windows-latest
    steps:
      # 安装 Inno Setup（通过 Chocolatey）
      - name: 安装 Inno Setup（通过 Chocolatey）
        run: choco install innosetup -y
        shell: powershell

      # 查找 ISCC.exe 路径并设置环境变量
      - name: 查找 ISCC.exe 路径并设置环境变量
        run: |
          $path = Get-Command ISCC.exe | Select-Object -ExpandProperty Source
          $envLine = "ISCC_PATH=$($path -replace '`r','' -replace '`n','')"
          [System.IO.File]::AppendAllText($env:GITHUB_ENV, "$envLine`n", [System.Text.Encoding]::UTF8)
          Set-Content -Path iscc_path.txt -Value $path -Encoding UTF8
        shell: powershell

      # 上传 ISCC 路径文件（可选）
      - name: 上传 ISCC 路径文件（可选）
        uses: actions/upload-artifact@v4
        with:
          name: iscc-path
          path: iscc_path.txt

  setup-conda-environment:
    runs-on: windows-latest
    needs: install-inno  # 确保安装 Inno 后再执行
    steps:
      # 安装 Miniconda
      - name: 安装 Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          env-name: py-xiaozhi
          python-version: "3.10"
          auto-update-conda: true
          auto-activate-base: false

      # 安装 Python 依赖
      - name: 安装 Python 依赖（pip + conda + pyinstaller）
        shell: bash
        run: |
          # 初始化 Conda 环境
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda activate py-xiaozhi

          # 安装要求的依赖
          pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple
          conda install pyqt=5.15.10 opencv=4.10.0 -y
          pip install pyinstaller

  clone-unifypy:
    runs-on: windows-latest
    needs: setup-conda-environment  # 确保设置 Conda 后再拉取 UnifyPy
    steps:
      # 拉取 UnifyPy 仓库
      - name: 拉取 UnifyPy 仓库
        run: |
          git clone https://github.com/huangjunsen0406/UnifyPy.git
        shell: bash

      # 运行 UnifyPy 构建项目
      - name: 运行 UnifyPy 构建项目
        run: |
          python UnifyPy/main.py . --config build.json
        shell: bash
