name: Setup Inno Setup

on:
  push:
    branches:
      - main

jobs:
  install-inno:
    runs-on: windows-latest

    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 安装 Inno Setup（通过 Chocolatey）
        run: choco install innosetup -y
        shell: powershell

      - name: 查找 ISCC.exe 路径并写入 build.json
        run: |
          # 获取 ISCC 路径
          $isccPath = Get-Command ISCC.exe | Select-Object -ExpandProperty Source

          # 读取 JSON 内容
          $jsonPath = "build.json"
          $json = Get-Content $jsonPath -Raw | ConvertFrom-Json

          # 设置新的 Inno Setup 路径
          $json.inno_setup_path = $isccPath

          # 写回 JSON 文件，格式化为 UTF-8 编码
          $json | ConvertTo-Json -Depth 10 | Out-File -FilePath $jsonPath -Encoding UTF8
        shell: powershell

      - name: 上传 build.json（可选）
        uses: actions/upload-artifact@v4
        with:
          name: updated-build-config
          path: build.json
