name: Setup Inno Setup, Conda, and Build

on:
  push:
    branches:
      - main

env:
  PYTHONIOENCODING: utf-8
  PYTHONUTF8: 1
  # 设置默认编码为UTF-8
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

jobs:
  setup-and-build:
    runs-on: windows-latest
    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v4

      # 安装 Inno Setup
      - name: 安装 Inno Setup（通过 Chocolatey）
        run: choco install innosetup -y
        shell: powershell

      # 下载 ChineseSimplified.isl 文件
      - name: 下载中文语言文件
        run: |
          $languageDir = "C:\Program Files (x86)\Inno Setup 6\Languages"
          
          # 确保目录存在
          if (-not (Test-Path $languageDir)) {
            New-Item -ItemType Directory -Path $languageDir -Force
          }
          
          # 下载中文语言文件
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/Unofficial/ChineseSimplified.isl" -OutFile "$languageDir\ChineseSimplified.isl"
          
          Write-Host "已下载中文语言文件到 $languageDir\ChineseSimplified.isl"
          
          # 验证文件是否存在
          if (Test-Path "$languageDir\ChineseSimplified.isl") {
            Write-Host "文件下载成功！"
          } else {
            Write-Error "文件下载失败！"
            exit 1
          }
        shell: powershell

      # 查找 ISCC.exe 路径并更新 build.json
      - name: 查找 ISCC.exe 路径并更新 build.json
        run: |
          # 确保PowerShell使用UTF-8编码
          $OutputEncoding = [System.Text.Encoding]::UTF8
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          
          # 获取 ISCC 路径
          $isccPath = Get-Command ISCC.exe | Select-Object -ExpandProperty Source
          
          # 设置环境变量
          $envLine = "ISCC_PATH=$($isccPath -replace '`r','' -replace '`n','')"
          [System.IO.File]::AppendAllText($env:GITHUB_ENV, "$envLine`n", [System.Text.Encoding]::UTF8)
          
          # 读取 JSON 内容
          $jsonPath = "build.json"
          $json = Get-Content $jsonPath -Raw | ConvertFrom-Json
          
          # 设置新的 Inno Setup 路径
          $json.inno_setup_path = $isccPath
          
          # 写回 JSON 文件，格式化为 UTF-8 编码
          $json | ConvertTo-Json -Depth 10 | Out-File -FilePath $jsonPath -Encoding UTF8
          
          Write-Host "已更新 build.json 中的 Inno Setup 路径为: $isccPath"
        shell: powershell

      # 安装 Miniconda 和 Conda
      - name: 安装 Miniconda 和 Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: py-xiaozhi

      # 创建 Conda 环境并安装依赖
      - name: 创建 Conda 环境 py-xiaozhi
        shell: bash -el {0}
        run: |
          # 设置UTF-8编码
          export PYTHONIOENCODING=utf-8
          export PYTHONUTF8=1
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
          
          conda create -n py-xiaozhi python=3.10 -y

      # 创建一个简单的 requirements.txt 文件（如果不存在）
      - name: 创建 requirements.txt
        run: |
          if (-not (Test-Path "requirements.txt")) {
            Set-Content -Path "requirements.txt" -Value ""
          }
        shell: powershell

      # 按教程顺序安装 Python 依赖和系统依赖
      - name: 安装依赖（按教程顺序）
        shell: bash -el {0}
        run: |
          # 设置UTF-8编码
          export PYTHONIOENCODING=utf-8
          export PYTHONUTF8=1
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
          
          conda activate py-xiaozhi
          
          # 1. 先安装系统依赖 - FFmpeg 和 Opus（通过 conda 明确指定通道）
          conda install conda-forge::libopus -y
          conda install conda-forge::ffmpeg -y
          
          # 2. 安装 PyQt5 和 OpenCV（必须用 conda 安装，不能用 pip）
          # 先安装 numpy，确保版本兼容
          conda install numpy=1.24.3 -y
          # 安装其他依赖
          conda install pyqt=5.15.10 opencv=4.10.0 -y
          
          # 3. 从 requirements.txt 安装其他依赖
          pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple
          
          # 4. 安装 Windows 特定依赖
          pip install wmi -i https://mirrors.aliyun.com/pypi/simple
          
          # 5. 安装 PyInstaller
          pip install pyinstaller
          
          # 6. 验证 NumPy 能否正确导入
          python -c "import numpy; import numpy.core; import numpy._core.multiarray; print('NumPy 导入成功!')"
          
          # 检查已安装的包
          echo "==== 查看已安装的包 ===="
          conda list

      # 拉取 UnifyPy 仓库
      - name: 拉取 UnifyPy 仓库
        run: git clone https://github.com/huangjunsen0406/UnifyPy.git
        shell: bash

      # 运行 UnifyPy 构建项目（去掉了 --verbose 参数）
      - name: 运行 UnifyPy 构建项目
        shell: bash -el {0}
        run: |
          conda activate py-xiaozhi
          # 设置编码和环境变量
          export PYTHONIOENCODING=utf-8
          export PYTHONUTF8=1
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
          
          # 为Python添加UTF-8默认编码
          echo "import sys; sys.stdout.reconfigure(encoding='utf-8'); sys.stderr.reconfigure(encoding='utf-8');" > setup_encoding.py
          
          # 列出当前目录结构，确认文件存在
          ls -la
          echo "查看build.json内容:"
          cat build.json
          
          # 运行UnifyPy时先通过encoding脚本
          python -c "import sys; sys.stdout.reconfigure(encoding='utf-8'); sys.stderr.reconfigure(encoding='utf-8'); exec(open('UnifyPy/main.py', encoding='utf-8').read())" . --config build.json

      # 只上传 Inno Setup 安装程序
      - name: 上传安装程序
        uses: actions/upload-artifact@v4
        with:
          name: installer-setup
          path: installer/
