name: Setup Inno Setup

on:
  push:
    branches:
      - main

jobs:
  install-inno:
    runs-on: windows-latest

    steps:
      - name: 安装 Inno Setup（通过 Chocolatey）
        run: choco install innosetup -y
        shell: powershell

      - name: 查找 ISCC.exe 路径并设置环境变量
        run: |
          $path = Get-Command ISCC.exe | Select-Object -ExpandProperty Source
          $envLine = "ISCC_PATH=$($path -replace '`r','' -replace '`n','')"
          [System.IO.File]::AppendAllText($env:GITHUB_ENV, "$envLine`n", [System.Text.Encoding]::UTF8)

          # （可选）写入一个临时文件中方便上传或调试
          Set-Content -Path iscc_path.txt -Value $path -Encoding UTF8
        shell: powershell

      - name: 上传 ISCC 路径文件（可选）
        uses: actions/upload-artifact@v4
        with:
          name: iscc-path
          path: iscc_path.txt
