name: Setup Inno Setup

on:
  push:
    branches:
      - main

jobs:
  install-inno:
    runs-on: windows-latest

    steps:
      - name: 安装 Inno Setup（通过 Chocolatey）
        run: choco install innosetup -y
        shell: powershell

      - name: 查找 ISCC.exe 路径并设置环境变量
        run: |
          # 获取 ISCC.exe 完整路径
          $path = Get-Command ISCC.exe | Select-Object -ExpandProperty Source

          # 输出调试信息
          Write-Output "ISCC 安装路径: $path"

          # 构造环境变量行（处理换行符等潜在问题）
          $envLine = "ISCC_PATH=$($path -replace '`r','' -replace '`n','')"

          # 使用 .NET 方法以 UTF-8 编码写入 GitHub 环境变量文件
          [System.IO.File]::AppendAllText($env:GITHUB_ENV, "$envLine`n", [System.Text.Encoding]::UTF8)
        shell: powershell

      - name: 输出 ISCC 安装路径（验证环境变量）
        run:  Write-Output ("Inno Setup 安装路径是：{0}" -f $env:ISCC_PATH)
        shell: powershell
