name: Setup Inno Setup, Conda, and Build

on:
  push:
    branches:
      - main

jobs:
  setup-and-build:
    runs-on: windows-latest
    steps:
      # 安装 Inno Setup
      - name: 安装 Inno Setup（通过 Chocolatey）
        run: choco install innosetup -y
        shell: powershell

      # 查找 ISCC.exe 路径并设置环境变量
      - name: 查找 ISCC.exe 路径并设置环境变量
        run: |
          $path = Get-Command ISCC.exe | Select-Object -ExpandProperty Source
          $envLine = "ISCC_PATH=$($path -replace '`r','' -replace '`n','')"
          [System.IO.File]::AppendAllText($env:GITHUB_ENV, "$envLine`n", [System.Text.Encoding]::UTF8)
          Set-Content -Path iscc_path.txt -Value $path -Encoding UTF8
        shell: powershell

      # 安装 Miniconda 和 Conda
      - name: 安装 Miniconda 和 Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          auto-update-conda: true
          auto-activate-base: false

      # 创建 Conda 环境并安装依赖
      - name: 创建 Conda 环境 py-xiaozhi
        run: |
          conda create -n py-xiaozhi python=3.10 -y
        shell: powershell

      # 安装 Python 依赖（pip + conda + pyinstaller）
      - name: 安装 Python 依赖（pip + conda + pyinstaller）
        run: |
          # 激活 Conda 环境
          & "$(conda info --base)\Scripts\activate" py-xiaozhi

          # 安装依赖
          pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple
          conda install pyqt=5.15.10 opencv=4.10.0 -y
          pip install pyinstaller
        shell: powershell

      # 拉取 UnifyPy 仓库
      - name: 拉取 UnifyPy 仓库
        run: |
          git clone https://github.com/huangjunsen0406/UnifyPy.git
        shell: powershell

      # 运行 UnifyPy 构建项目
      - name: 运行 UnifyPy 构建项目
        run: |
          $env:PYTHONIOENCODING = "utf-8"
          python UnifyPy/main.py . --config build.json
        shell: powershell
